language: node_js # 构建所需的语言环境
node_js:
  - "v14.18.0"  # 对应的版本
branches:
  only:
  - master    # 构建的分支
cache:
  directories:
  - node_modules # 依赖缓存的目录
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
install:
 - npm install # 安装依赖
script:
- npm run build #构建
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  keep_history: true
  local-dir: ./_book/ ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master